# Generated by Django 2.2.4 on 2019-08-16 16:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='outgoinginvoice',
            name='date_new',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
