# Generated by Django 2.2.4 on 2019-08-16 16:26

import datetime

import pytz
from django.db import migrations, models

from tallybill import settings


def datetime_now_tz():
    return datetime.datetime.now(tz=pytz.timezone(settings.TIME_ZONE))

class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_copy_tmp_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='outgoinginvoice',
            name='date',
            field=models.DateTimeField(default=datetime_now_tz),
        ),
    ]
