# Generated by Django 2.2.4 on 2019-08-16 16:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_copy_datetime_back'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='outgoinginvoice',
            name='date_new',
        ),
    ]
